/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uaspbokelompok;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author iilha
 */
public final class MenuHalamanUser extends javax.swing.JFrame {
    /**
     * Creates new form MenuLogin
     */
    public MenuHalamanUser() {
        initComponents();
        initComboBox();
    }

    public void initComboBox() {
        jcomboboxLayanan.addItem("Motor");
        jcomboboxLayanan.addItem("Mobil");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdCustomer = new javax.swing.JTextField();
        txtNoTelepon = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        buttonSend = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelRincian = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jcomboboxLayanan = new javax.swing.JComboBox<>();
        buttonBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Menu Pesanan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 6, -1, -1));

        jLabel2.setText("ID Customer :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 47, -1, -1));

        jLabel3.setText("No. Telepon :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 127, -1, -1));

        jLabel4.setText("Alamat :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 167, -1, -1));

        txtIdCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 44, 150, -1));

        txtNoTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTeleponActionPerformed(evt);
            }
        });
        getContentPane().add(txtNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 124, 150, -1));

        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 164, 150, -1));

        buttonSend.setText("Send");
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 388, -1, -1));

        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 388, -1, -1));

        jLabel5.setText("Nama :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, -1, -1));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 84, 150, -1));

        tabelRincian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Customer", "Nama", "No. Telepon", "Alamat", "Layanan Antar/Jemput"
            }
        ));
        tabelRincian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRincianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelRincian);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 44, 392, 279));

        jLabel6.setText("Layanan Antar/Jemput");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, -1, -1));

        jcomboboxLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih" }));
        getContentPane().add(jcomboboxLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 204, 150, -1));

        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 388, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Menu Pesanan.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
      try {
        // Validasi jika ada field yang kosong
        if (txtIdCustomer.getText().isEmpty() || txtNama.getText().isEmpty() || 
            txtNoTelepon.getText().isEmpty() || txtAlamat.getText().isEmpty() || 
            jcomboboxLayanan.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(this, "Harap isi semua field dengan benar!", "Validasi", JOptionPane.WARNING_MESSAGE);
            return; // Menghentikan proses jika ada field kosong
        }

        // Query SQL untuk menyimpan data
        String sql = "INSERT INTO menupesanan (id_customer, nama, no_telepon, alamat, layanan) VALUES (?, ?, ?, ?, ?)";
        java.sql.Connection conn = KoneksiDB.konek();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        // Mengisi parameter query
        pst.setString(1, txtIdCustomer.getText());
        pst.setString(2, txtNama.getText());
        pst.setString(3, txtNoTelepon.getText());
        pst.setString(4, txtAlamat.getText());
        pst.setString(5, jcomboboxLayanan.getSelectedItem().toString());

        // Eksekusi query
        pst.execute();
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke database!");

        // Tambahkan data ke JTable
        DefaultTableModel model = (DefaultTableModel) tabelRincian.getModel();
        model.addRow(new Object[]{txtIdCustomer.getText(), txtNama.getText(), txtNoTelepon.getText(), txtAlamat.getText(), jcomboboxLayanan.getSelectedItem().toString()});

        // Kosongkan input setelah data ditambahkan
        txtIdCustomer.setText("");
        txtNama.setText("");
        txtNoTelepon.setText("");
        txtAlamat.setText("");
        jcomboboxLayanan.setSelectedIndex(0);  
        
    } catch (SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(MenuHalamanUser.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_buttonSendActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtIdCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCustomerActionPerformed

    private void txtNoTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTeleponActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
          new MenuLogin().setVisible(true); // Kembali ke Menu Login
            dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        // Pastikan pengguna memilih baris yang akan diedit
        int selectedRow = tabelRincian.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

        try {
        // Ambil data dari form input
            String idCustomer = txtIdCustomer.getText();
            String nama = txtNama.getText();
            String noTelepon = txtNoTelepon.getText();
            String alamat = txtAlamat.getText();
            String layanan = jcomboboxLayanan.getSelectedItem().toString();

        // Validasi input
        if (idCustomer.isEmpty() || nama.isEmpty() || noTelepon.isEmpty() || alamat.isEmpty() || layanan.equals("Pilih")) {
            JOptionPane.showMessageDialog(this, "Harap isi semua field dengan benar!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Query SQL untuk update data di database
            String sql = "UPDATE menupesanan SET nama = ?, no_telepon = ?, alamat = ?, layanan = ? WHERE id_customer = ?";
            java.sql.Connection conn = KoneksiDB.konek();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            // Isi parameter query
            pst.setString(1, nama);
            pst.setString(2, noTelepon);
            pst.setString(3, alamat);
            pst.setString(4, layanan);
            pst.setString(5, idCustomer);

        // Eksekusi query
        int rowsUpdated = pst.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");

            // Update data di JTable
            DefaultTableModel model = (DefaultTableModel) tabelRincian.getModel();
            model.setValueAt(idCustomer, selectedRow, 0);
            model.setValueAt(nama, selectedRow, 1);
            model.setValueAt(noTelepon, selectedRow, 2);
            model.setValueAt(alamat, selectedRow, 3);
            model.setValueAt(layanan, selectedRow, 4);

            // Kosongkan input form
            txtIdCustomer.setText("");
            txtNama.setText("");
            txtNoTelepon.setText("");
            txtAlamat.setText("");
            jcomboboxLayanan.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data. Cek ID Customer!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException | ClassNotFoundException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void tabelRincianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRincianMouseClicked
        // TODO add your handling code here:
        // Ambil baris yang dipilih
        int selectedRow = tabelRincian.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tabelRincian.getModel();

        // Isi form dengan data dari JTable
            txtIdCustomer.setText(model.getValueAt(selectedRow, 0).toString());
            txtNama.setText(model.getValueAt(selectedRow, 1).toString());
            txtNoTelepon.setText(model.getValueAt(selectedRow, 2).toString());
            txtAlamat.setText(model.getValueAt(selectedRow, 3).toString());
            jcomboboxLayanan.setSelectedItem(model.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_tabelRincianMouseClicked

 /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuHalamanUser().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcomboboxLayanan;
    private javax.swing.JTable tabelRincian;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtIdCustomer;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoTelepon;
    // End of variables declaration//GEN-END:variables
}
