/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uaspbokelompok;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author iilha
 */
public final class OrderDetail extends javax.swing.JFrame {

    /**
     * Creates new form TampilanGUI
     */
    public OrderDetail() {
        initComponents();
        initComboBox();
        loadDataUser();
        setTanggalOtomatis();
        loadDataProsesPesanan();

    }
    
    public void initComboBox() {
        jcomboboxLayanan.addItem("Motor");
        jcomboboxLayanan.addItem("Mobil");
    }
    
    private void loadDataProsesPesanan() {
    try {
        // Koneksi ke database
        java.sql.Connection conn = KoneksiDB.konek();
        String sql = "SELECT * FROM prosespesanan"; // Query SQL untuk mengambil semua data
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        // Menghapus data lama di JTable (jika ada)
        DefaultTableModel model = (DefaultTableModel) tabelProsesPesanan.getModel();
        model.setRowCount(0);

        // Iterasi data dari ResultSet ke JTable
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("order_id"),
                rs.getTimestamp("tanggalmasuk"),
                rs.getString("nama_customer"),
                rs.getString("no_telepon"),
                rs.getString("alamat"),
                rs.getString("layanan"),
                rs.getString("metode"),
                rs.getDouble("hargatotal")
            });
        }
    } catch (SQLException | ClassNotFoundException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
}


    private void setTanggalOtomatis() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalSekarang = sdf.format(new Date());  // Format tanggal saat ini
        txtTanggalMasuk.setText(tanggalSekarang);  // Menetapkan tanggal otomatis ke JTextField
    }
    
    public void loadDataUser() {
    // Nama kolom di JTable
   String[] kolom = {"ID Customer", "Nama", "No Telepon", "Alamat", "Layanan"};
        DefaultTableModel model = new DefaultTableModel(null, kolom);

        try {
            // Gunakan metode konek() dari KoneksiDB
            Connection conn = KoneksiDB.konek();
            Statement stmt = conn.createStatement();

            // Query untuk mengambil data dari tabel
            String sql = "SELECT * FROM menupesanan";
            ResultSet rs = stmt.executeQuery(sql);

            // Iterasi data dari ResultSet ke JTable
            while (rs.next()) {
                String idCustomer = rs.getString("id_customer");
                String nama = rs.getString("nama");
                String noTelepon = rs.getString("no_telepon");
                String alamat = rs.getString("alamat");
                String layanan = rs.getString("layanan");

                // Tambahkan data ke model
                String[] data = {idCustomer, nama, noTelepon, alamat, layanan};
                model.addRow(data);
            }

            // Set model ke JTable
            tabelRincian.setModel(model);

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdOrder = new javax.swing.JTextField();
        txtNoTelepon = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtBerat = new javax.swing.JTextField();
        jcomboboxLayanan = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        txtHargaTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProsesPesanan = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jcomboboxMetode = new javax.swing.JComboBox<>();
        txtTanggalMasuk = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonSubmit = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelRincian = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel1.setText("Order Detail");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 6, -1, -1));

        jLabel2.setText("Order ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 39, -1, -1));

        jLabel3.setText("No. Telepon");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 156, -1, -1));

        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 196, -1, -1));

        jLabel5.setText("Layanan Antar/Jemput");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 282, -1, -1));

        jLabel6.setText("Kg");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 282, -1, -1));

        jLabel7.setText("Harga Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));
        getContentPane().add(txtIdOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 36, 207, -1));
        getContentPane().add(txtNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 156, 207, -1));
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 196, 207, 77));
        getContentPane().add(txtBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 279, 25, -1));

        jcomboboxLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", " " }));
        getContentPane().add(jcomboboxLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 279, -1, -1));

        btnHitung.setText("Count");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));
        getContentPane().add(txtHargaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 120, -1));

        tabelProsesPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Tanggal Masuk", "Nama Customer", "No. Telepon", "Alamat", "Layanan", "Metode Cuci", "Harga Total"
            }
        ));
        jScrollPane1.setViewportView(tabelProsesPesanan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 790, 210));

        jLabel8.setText("Metode Cuci");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 338, -1, -1));

        jcomboboxMetode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Cuci Kering", "Cuci Kering + Setrika" }));
        getContentPane().add(jcomboboxMetode, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 335, -1, -1));

        txtTanggalMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalMasukActionPerformed(evt);
            }
        });
        getContentPane().add(txtTanggalMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 76, 207, -1));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 116, 207, -1));

        jLabel10.setText("Tanggal Masuk");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 79, -1, -1));

        jLabel11.setText("Nama Customer");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 119, -1, -1));

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, -1));

        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 530, -1, -1));

        tabelRincian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No Customer", "Nama", "No Telepon", "Alamat", "Layanan"
            }
        ));
        tabelRincian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRincianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelRincian);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 490, 220));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/TampilanOrderDetail.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:                                         
    // Validasi input: Pastikan semua field diisi
    if (txtIdOrder.getText().isEmpty() ||
        txtNama.getText().isEmpty() ||
        txtNoTelepon.getText().isEmpty() ||
        txtAlamat.getText().isEmpty() ||
        jcomboboxLayanan.getSelectedIndex() == 0 ||
        jcomboboxMetode.getSelectedIndex() == 0 ||
        txtHargaTotal.getText().isEmpty()) {

        JOptionPane.showMessageDialog(this, "Harap isi semua field dengan benar!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // Query SQL untuk menyimpan data ke tabel prosespesanan
        String sql = "INSERT INTO prosespesanan (order_id, tanggalmasuk, nama_customer, no_telepon, alamat, layanan, metode, hargatotal) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        java.sql.Connection conn = KoneksiDB.konek();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        // Mengisi parameter query
        pst.setInt(1, Integer.parseInt(txtIdOrder.getText())); // Mengisi order_id
        pst.setTimestamp(2, new java.sql.Timestamp(System.currentTimeMillis())); // Mengisi tanggalmasuk dengan waktu saat ini
        pst.setString(3, txtNama.getText()); // Mengisi nama_customer
        pst.setString(4, txtNoTelepon.getText()); // Mengisi no_telepon
        pst.setString(5, txtAlamat.getText()); // Mengisi alamat
        pst.setString(6, jcomboboxLayanan.getSelectedItem().toString()); // Mengisi layanan
        pst.setString(7, jcomboboxMetode.getSelectedItem().toString()); // Mengisi metode
        pst.setDouble(8, Double.parseDouble(txtHargaTotal.getText())); // Mengisi hargatotal

        // Eksekusi query
        pst.execute();
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke database!");

        // Tambahkan data ke JTable
        DefaultTableModel model = (DefaultTableModel) tabelProsesPesanan.getModel();
        model.addRow(new Object[]{
            txtIdOrder.getText(),
            new java.sql.Timestamp(System.currentTimeMillis()),
            txtNama.getText(),
            txtNoTelepon.getText(),
            txtAlamat.getText(),
            jcomboboxLayanan.getSelectedItem().toString(),
            jcomboboxMetode.getSelectedItem().toString(),
            txtHargaTotal.getText()
        });

        // Kosongkan input setelah data ditambahkan
        txtIdOrder.setText("");
        txtNama.setText("");
        txtNoTelepon.setText("");
        txtAlamat.setText("");
        jcomboboxLayanan.setSelectedIndex(0);
        jcomboboxMetode.setSelectedIndex(0);
        txtHargaTotal.setText("");

    } catch (SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(OrderDetail.class.getName()).log(Level.SEVERE, null, ex);
    }

    // Memuat ulang data pada tabel
    loadDataProsesPesanan();

    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        new MenuHalamanAdmin().setVisible(true); // Pergi ke MenuHalaman Admin
            dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void tabelRincianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRincianMouseClicked
        // TODO add your handling code here
        int selectedRow = tabelRincian.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tabelRincian.getModel();

    // Isi form dengan data dari JTable
         txtIdOrder.setText(model.getValueAt(selectedRow, 0).toString());
        txtNama.setText(model.getValueAt(selectedRow, 1).toString());
         txtNoTelepon.setText(model.getValueAt(selectedRow, 2).toString());
         txtAlamat.setText(model.getValueAt(selectedRow, 3).toString());
         jcomboboxLayanan.setSelectedItem(model.getValueAt(selectedRow, 4).toString());
        loadDataUser();
    }//GEN-LAST:event_tabelRincianMouseClicked

    private void txtTanggalMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalMasukActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        try {
        // Ambil nilai dari input
        String layanan = jcomboboxLayanan.getSelectedItem().toString();
        String metode = jcomboboxMetode.getSelectedItem().toString();
        double berat = Double.parseDouble(txtBerat.getText());

        // Harga dasar
        double hargaDasar = 6000; // Contoh: harga per Kg adalah 6000
        double biayaLayanan = 0;
        double biayaMetode = 0;

        // Hitung biaya tambahan untuk layanan antar/jemput
        if (layanan.equalsIgnoreCase("Motor")) {
            biayaLayanan = 2000; // Biaya tambahan untuk layanan antar/jemput
        } else if (layanan.equalsIgnoreCase("Mobil")) {
            biayaLayanan = 10000; // Biaya tambahan untuk layanan antar/jemput
        }
        
        // Hitung biaya tambahan berdasarkan metode cuci
        if (metode.equalsIgnoreCase("Cuci Kering")) {
            biayaMetode = 5000; // Biaya tambahan untuk metode kilat
        } else if (metode.equalsIgnoreCase("Cuci Kering + Setrika")) {
            biayaMetode = 7000; // Biaya tambahan untuk metode premium
        }

        // Hitung total harga
        double hargaTotal = (hargaDasar + biayaMetode) * berat + biayaLayanan;

        // Tampilkan hasil perhitungan ke txtHargaTotal
        txtHargaTotal.setText(String.valueOf(hargaTotal));
    } catch (NumberFormatException e) {
        // Jika input berat tidak valid
        JOptionPane.showMessageDialog(this, "Masukkan berat yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }   
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcomboboxLayanan;
    private javax.swing.JComboBox<String> jcomboboxMetode;
    private javax.swing.JTable tabelProsesPesanan;
    private javax.swing.JTable tabelRincian;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtHargaTotal;
    private javax.swing.JTextField txtIdOrder;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoTelepon;
    private javax.swing.JTextField txtTanggalMasuk;
    // End of variables declaration//GEN-END:variables
}
